version: '3'

services:
    # db:
    #     image: mysql:5.7
    #     environment:
    #         MYSQL_ROOT_PASSWORD: password
    #         POSTGRES_HOST_AUTH_METHOD: 'trust'
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./db/mysql/volumes:/var/lib/mysql

    web:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p -e production"
        volumes:
            - .:/myapp
            - gem_data:/usr/local/bundle
        ports:
            - 8080:8080
        tty: true
        stdin_open: true


    nginx:
        build:
          context: ./nginx_docker_prod

        volumes:
          - public-data:/app_name/public
          - tmp-data:/app_name/tmp
        ports:
          - 80:80
        depends_on:
          - web

volumes:
  gem_data: